import { addDays, format, isWeekend, parseISO, setHours, setMinutes } from "date-fns";
import { calcPayslip } from "./payroll";
import { hashString } from "./utils";
import type {
  AttendanceRecord,
  ChatMessage,
  Claim,
  CompanyDoc,
  CompanyInfo,
  Employee,
  Kpi,
  LeaveBalance,
  LeaveRequest,
  OpenPosition,
  PayrollConnector,
  Payslip,
  RetentionSignal,
  Review,
  Role,
  SyncJob,
} from "./types";

export const COMPANY: CompanyInfo = {
  name: "Arunika",
  legalName: "PT Arunika Digital",
  industry: "Product studio",
  hq: "Kebayoran Baru, Jakarta Selatan",
  officeLat: -6.2431,
  officeLng: 106.802,
  founded: 2019,
  headcount: 18,
};

export const COMPETENCIES = [
  "Dampak",
  "Kolaborasi",
  "Kepemilikan",
  "Kualitas",
  "Pertumbuhan",
] as const;

export const DEMO_PERSONAS: { role: Role; userId: string; blurb: string }[] = [
  {
    role: "hr",
    userId: "lestari",
    blurb: "Kelola database karyawan, payroll, cuti, dan modul AI.",
  },
  {
    role: "manager",
    userId: "raka",
    blurb: "Pantau tim engineering, setujui cuti, tulis review kinerja.",
  },
  {
    role: "employee",
    userId: "nadia",
    blurb: "Presensi, sisa cuti, slip gaji, klaim, dan dokumen perusahaan.",
  },
];

const TODAY = "2026-09-11";

function emp(partial: Employee): Employee {
  return partial;
}

export const EMPLOYEES: Employee[] = [
  emp({
    id: "maya",
    nik: "ARK-2019-001",
    name: "Maya Sari",
    preferredName: "Maya",
    email: "maya.sari@arunika.id",
    phone: "0812-1100-1001",
    initials: "MS",
    tone: 0,
    title: "Chief Executive Officer",
    department: "executive",
    managerId: null,
    location: "Jakarta",
    joinDate: "2019-03-04",
    status: "active",
    contractType: "permanent",
    grade: "E1",
    gender: "F",
    birthDate: "1986-07-12",
    address: "Jl. Wolter Monginsidi No. 18",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099001",
    npwp: "10.221.884.3-012.000",
    ptkp: "K/1",
    bpjsKes: "0001872211001",
    bpjsTk: "8801122001",
    salary: 85_000_000,
    allowance: 12_000_000,
    skills: ["Leadership", "Fundraising", "Product strategy", "Public speaking"],
    certifications: [{ name: "Executive Leadership", issuer: "INSEAD", year: 2022 }],
    facilities: ["Mobil dinas", "Asuransi keluarga", "Parking"],
    emergencyContact: { name: "Arif Sari", relation: "Suami", phone: "0812-1100-1099" },
    bio: "Mendirikan Arunika pada 2019. Fokus pada produk yang terasa manusiawi.",
  }),
  emp({
    id: "dimas",
    nik: "ARK-2019-002",
    name: "Dimas Prasetyo",
    preferredName: "Dimas",
    email: "dimas.prasetyo@arunika.id",
    phone: "0813-2200-2002",
    initials: "DP",
    tone: 1,
    title: "Chief Technology Officer",
    department: "engineering",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2019-04-15",
    status: "active",
    contractType: "permanent",
    grade: "E2",
    gender: "M",
    birthDate: "1988-11-02",
    address: "Jl. Kemang Raya No. 42",
    city: "Jakarta Selatan",
    bankName: "Mandiri",
    bankAccount: "1280099002",
    npwp: "10.221.884.3-012.002",
    ptkp: "K/2",
    bpjsKes: "0001872211002",
    bpjsTk: "8801122002",
    salary: 65_000_000,
    allowance: 8_000_000,
    skills: ["System design", "TypeScript", "Hiring", "Architecture"],
    certifications: [{ name: "AWS Solutions Architect", issuer: "Amazon", year: 2023 }],
    facilities: ["Laptop MacBook", "Asuransi keluarga"],
    emergencyContact: { name: "Rina Prasetyo", relation: "Istri", phone: "0813-2200-2099" },
    bio: "Membangun fondasi teknik Arunika dari hari pertama.",
  }),
  emp({
    id: "lestari",
    nik: "ARK-2020-007",
    name: "Lestari Wulandari",
    preferredName: "Lestari",
    email: "lestari.wulandari@arunika.id",
    phone: "0812-3300-3003",
    initials: "LW",
    tone: 2,
    title: "Chief People Officer",
    department: "people",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2020-01-08",
    status: "active",
    contractType: "permanent",
    grade: "E2",
    gender: "F",
    birthDate: "1989-02-20",
    address: "Jl. Cipete Raya No. 9",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099003",
    npwp: "10.221.884.3-012.003",
    ptkp: "K/0",
    bpjsKes: "0001872211003",
    bpjsTk: "8801122003",
    salary: 48_000_000,
    allowance: 6_000_000,
    skills: ["People ops", "Coaching", "Kompensasi", "Industrial relations"],
    certifications: [{ name: "SHRM-SCP", issuer: "SHRM", year: 2021 }],
    facilities: ["Laptop", "Asuransi keluarga"],
    emergencyContact: { name: "Budi Wulandari", relation: "Suami", phone: "0812-3300-3099" },
    bio: "Merancang sistem people yang hangat tanpa kehilangan ketertiban.",
  }),
  emp({
    id: "andi",
    nik: "ARK-2020-011",
    name: "Andi Wijaya",
    preferredName: "Andi",
    email: "andi.wijaya@arunika.id",
    phone: "0813-4400-4004",
    initials: "AW",
    tone: 3,
    title: "Head of Product",
    department: "product",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2020-06-01",
    status: "active",
    contractType: "permanent",
    grade: "M1",
    gender: "M",
    birthDate: "1990-05-14",
    address: "Jl. Senopati No. 27",
    city: "Jakarta Selatan",
    bankName: "BNI",
    bankAccount: "1280099004",
    npwp: "10.221.884.3-012.004",
    ptkp: "TK/0",
    bpjsKes: "0001872211004",
    bpjsTk: "8801122004",
    salary: 45_000_000,
    allowance: 5_000_000,
    skills: ["Product discovery", "Roadmapping", "Research", "SQL"],
    certifications: [{ name: "Reforge Product Strategy", issuer: "Reforge", year: 2024 }],
    facilities: ["Laptop"],
    emergencyContact: { name: "Sari Wijaya", relation: "Ibu", phone: "0813-4400-4099" },
    bio: "Menjaga produk tetap tajam pada masalah yang layak dipecahkan.",
  }),
  emp({
    id: "sinta",
    nik: "ARK-2021-014",
    name: "Sinta Rahayu",
    preferredName: "Sinta",
    email: "sinta.rahayu@arunika.id",
    phone: "0812-5500-5005",
    initials: "SR",
    tone: 4,
    title: "Head of Finance",
    department: "finance",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2021-02-10",
    status: "active",
    contractType: "permanent",
    grade: "M1",
    gender: "F",
    birthDate: "1987-09-30",
    address: "Jl. Fatmawati No. 11",
    city: "Jakarta Selatan",
    bankName: "Mandiri",
    bankAccount: "1280099005",
    npwp: "10.221.884.3-012.005",
    ptkp: "K/1",
    bpjsKes: "0001872211005",
    bpjsTk: "8801122005",
    salary: 38_000_000,
    allowance: 4_000_000,
    skills: ["Payroll", "PPh 21", "Forecasting", "Audit"],
    certifications: [{ name: "Brevet A/B", issuer: "IKPI", year: 2018 }],
    facilities: ["Laptop"],
    emergencyContact: { name: "Dedi Rahayu", relation: "Suami", phone: "0812-5500-5099" },
    bio: "Menjaga angka tetap jujur — termasuk gaji, pajak, dan benefit.",
  }),
  emp({
    id: "raka",
    nik: "ARK-2021-018",
    name: "Raka Putra",
    preferredName: "Raka",
    email: "raka.putra@arunika.id",
    phone: "0813-6600-6006",
    initials: "RP",
    tone: 5,
    title: "Engineering Manager",
    department: "engineering",
    managerId: "dimas",
    location: "Jakarta",
    joinDate: "2021-08-16",
    status: "active",
    contractType: "permanent",
    grade: "M2",
    gender: "M",
    birthDate: "1992-01-22",
    address: "Jl. Pondok Indah No. 3",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099006",
    npwp: "10.221.884.3-012.006",
    ptkp: "K/0",
    bpjsKes: "0001872211006",
    bpjsTk: "8801122006",
    salary: 35_000_000,
    allowance: 3_500_000,
    skills: ["People management", "React", "Coaching", "Delivery"],
    certifications: [{ name: "Manager Tools", issuer: "Manager Tools", year: 2023 }],
    facilities: ["Laptop"],
    emergencyContact: { name: "Intan Putra", relation: "Istri", phone: "0813-6600-6099" },
    bio: "Menjaga tim engineering tetap tenang saat rilis mendesak.",
  }),
  emp({
    id: "nadia",
    nik: "ARK-2022-024",
    name: "Nadia Kusuma",
    preferredName: "Nadia",
    email: "nadia.kusuma@arunika.id",
    phone: "0812-7700-7007",
    initials: "NK",
    tone: 0,
    title: "Senior Software Engineer",
    department: "engineering",
    managerId: "raka",
    location: "Jakarta",
    joinDate: "2022-03-07",
    status: "active",
    contractType: "permanent",
    grade: "IC3",
    gender: "F",
    birthDate: "1995-04-03",
    address: "Jl. Radio Dalam No. 8",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099007",
    npwp: "10.221.884.3-012.007",
    ptkp: "TK/0",
    bpjsKes: "0001872211007",
    bpjsTk: "8801122007",
    salary: 28_000_000,
    allowance: 2_500_000,
    skills: ["TypeScript", "React", "Node.js", "System design", "Mentoring"],
    certifications: [{ name: "CKAD", issuer: "CNCF", year: 2024 }],
    facilities: ["Laptop", "Monitor 27\""],
    emergencyContact: { name: "Rini Kusuma", relation: "Ibu", phone: "0812-7700-7099" },
    bio: "Membangun portal karyawan Humanis dari sisi teknik.",
  }),
  emp({
    id: "bima",
    nik: "ARK-2023-031",
    name: "Bima Santoso",
    preferredName: "Bima",
    email: "bima.santoso@arunika.id",
    phone: "0813-8800-8008",
    initials: "BS",
    tone: 1,
    title: "Software Engineer",
    department: "engineering",
    managerId: "raka",
    location: "Jakarta",
    joinDate: "2023-01-09",
    status: "active",
    contractType: "permanent",
    grade: "IC2",
    gender: "M",
    birthDate: "1997-08-19",
    address: "Jl. TB Simatupang No. 21",
    city: "Jakarta Selatan",
    bankName: "BNI",
    bankAccount: "1280099008",
    npwp: "10.221.884.3-012.008",
    ptkp: "TK/0",
    bpjsKes: "0001872211008",
    bpjsTk: "8801122008",
    salary: 16_000_000,
    allowance: 1_500_000,
    skills: ["TypeScript", "PostgreSQL", "API design"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Agus Santoso", relation: "Ayah", phone: "0813-8800-8099" },
    bio: "Engineer yang cepat — dan belakangan sering lembur.",
  }),
  emp({
    id: "fajar",
    nik: "ARK-2023-036",
    name: "Fajar Hidayat",
    preferredName: "Fajar",
    email: "fajar.hidayat@arunika.id",
    phone: "0812-9900-9009",
    initials: "FH",
    tone: 2,
    title: "QA Engineer",
    department: "engineering",
    managerId: "raka",
    location: "Jakarta",
    joinDate: "2023-05-02",
    status: "active",
    contractType: "permanent",
    grade: "IC2",
    gender: "M",
    birthDate: "1996-12-11",
    address: "Jl. Pasar Minggu No. 5",
    city: "Jakarta Selatan",
    bankName: "Mandiri",
    bankAccount: "1280099009",
    npwp: "10.221.884.3-012.009",
    ptkp: "K/0",
    bpjsKes: "0001872211009",
    bpjsTk: "8801122009",
    salary: 14_000_000,
    allowance: 1_200_000,
    skills: ["Test design", "Playwright", "Accessibility"],
    certifications: [{ name: "ISTQB Foundation", issuer: "ISTQB", year: 2022 }],
    facilities: ["Laptop"],
    emergencyContact: { name: "Dewi Hidayat", relation: "Istri", phone: "0812-9900-9099" },
    bio: "Menemukan bug sebelum pengguna yang menemukannya.",
  }),
  emp({
    id: "farah",
    nik: "ARK-2021-021",
    name: "Farah Azzahra",
    preferredName: "Farah",
    email: "farah.azzahra@arunika.id",
    phone: "0813-1010-1010",
    initials: "FA",
    tone: 3,
    title: "Lead Product Designer",
    department: "design",
    managerId: "dimas",
    location: "Jakarta",
    joinDate: "2021-11-01",
    status: "active",
    contractType: "permanent",
    grade: "IC3",
    gender: "F",
    birthDate: "1993-06-08",
    address: "Jl. Gunawarman No. 14",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099010",
    npwp: "10.221.884.3-012.010",
    ptkp: "TK/0",
    bpjsKes: "0001872211010",
    bpjsTk: "8801122010",
    salary: 24_000_000,
    allowance: 2_000_000,
    skills: ["Product design", "Design systems", "Facilitation", "Figma"],
    certifications: [],
    facilities: ["Laptop", "iPad"],
    emergencyContact: { name: "Laila Azzahra", relation: "Ibu", phone: "0813-1010-1099" },
    bio: "Merancang antarmuka yang terasa tenang, bukan ramai.",
  }),
  emp({
    id: "kirana",
    nik: "ARK-2026-052",
    name: "Kirana Putri",
    preferredName: "Kira",
    email: "kirana.putri@arunika.id",
    phone: "0812-1111-1111",
    initials: "KP",
    tone: 4,
    title: "Product Design Intern",
    department: "design",
    managerId: "farah",
    location: "Jakarta",
    joinDate: "2026-07-01",
    status: "probation",
    contractType: "intern",
    contractEnd: "2027-01-01",
    grade: "IN",
    gender: "F",
    birthDate: "2003-03-17",
    address: "Jl. Tebet Barat No. 2",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099011",
    npwp: "-",
    ptkp: "TK/0",
    bpjsKes: "0001872211011",
    bpjsTk: "8801122011",
    salary: 5_000_000,
    allowance: 500_000,
    skills: ["Figma", "Prototyping", "Visual design"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Wulan Putri", relation: "Ibu", phone: "0812-1111-1199" },
    bio: "Magang desain yang sedang mencari ritme kerja studio.",
  }),
  emp({
    id: "yoga",
    nik: "ARK-2022-027",
    name: "Yoga Pratama",
    preferredName: "Yoga",
    email: "yoga.pratama@arunika.id",
    phone: "0813-1212-1212",
    initials: "YP",
    tone: 5,
    title: "Product Manager",
    department: "product",
    managerId: "andi",
    location: "Jakarta",
    joinDate: "2022-09-12",
    status: "active",
    contractType: "permanent",
    grade: "IC3",
    gender: "M",
    birthDate: "1994-10-25",
    address: "Jl. Melawai No. 6",
    city: "Jakarta Selatan",
    bankName: "Mandiri",
    bankAccount: "1280099012",
    npwp: "10.221.884.3-012.012",
    ptkp: "K/1",
    bpjsKes: "0001872211012",
    bpjsTk: "8801122012",
    salary: 22_000_000,
    allowance: 2_000_000,
    skills: ["Discovery", "Analytics", "Writing", "SQL"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Nisa Pratama", relation: "Istri", phone: "0813-1212-1299" },
    bio: "Menulis brief yang rapat dan merapikan prioritas yang kacau.",
  }),
  emp({
    id: "citra",
    nik: "ARK-2024-041",
    name: "Citra Dewi",
    preferredName: "Citra",
    email: "citra.dewi@arunika.id",
    phone: "0812-1313-1313",
    initials: "CD",
    tone: 0,
    title: "HR Business Partner",
    department: "people",
    managerId: "lestari",
    location: "Jakarta",
    joinDate: "2024-02-05",
    status: "active",
    contractType: "permanent",
    grade: "IC2",
    gender: "F",
    birthDate: "1996-01-09",
    address: "Jl. Panglima Polim No. 19",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099013",
    npwp: "10.221.884.3-012.013",
    ptkp: "TK/0",
    bpjsKes: "0001872211013",
    bpjsTk: "8801122013",
    salary: 14_000_000,
    allowance: 1_200_000,
    skills: ["Employee relations", "Recruiting", "Onboarding", "Excel"],
    certifications: [{ name: "Certified HRBP", issuer: "HRCI", year: 2025 }],
    facilities: ["Laptop"],
    emergencyContact: { name: "Tono Dewi", relation: "Ayah", phone: "0812-1313-1399" },
    bio: "Mitra pertama manajer saat orang-orangnya sedang tidak baik-baik saja.",
  }),
  emp({
    id: "eko",
    nik: "ARK-2022-029",
    name: "Eko Nugroho",
    preferredName: "Eko",
    email: "eko.nugroho@arunika.id",
    phone: "0813-1414-1414",
    initials: "EN",
    tone: 1,
    title: "Finance Associate",
    department: "finance",
    managerId: "sinta",
    location: "Jakarta",
    joinDate: "2022-11-21",
    status: "active",
    contractType: "permanent",
    grade: "IC1",
    gender: "M",
    birthDate: "1998-07-07",
    address: "Jl. Mampang Prapatan No. 4",
    city: "Jakarta Selatan",
    bankName: "BNI",
    bankAccount: "1280099014",
    npwp: "10.221.884.3-012.014",
    ptkp: "TK/0",
    bpjsKes: "0001872211014",
    bpjsTk: "8801122014",
    salary: 12_000_000,
    allowance: 1_000_000,
    skills: ["Rekonsiliasi", "PPh 21", "Excel", "Accurate"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Sri Nugroho", relation: "Ibu", phone: "0813-1414-1499" },
    bio: "Menyusun angka payroll sampai selisihnya nol.",
  }),
  emp({
    id: "putri",
    nik: "ARK-2023-033",
    name: "Putri Melati",
    preferredName: "Putri",
    email: "putri.melati@arunika.id",
    phone: "0812-1515-1515",
    initials: "PM",
    tone: 2,
    title: "Brand Lead",
    department: "marketing",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2023-03-13",
    status: "active",
    contractType: "permanent",
    grade: "IC3",
    gender: "F",
    birthDate: "1994-02-28",
    address: "Jl. Antasari No. 10",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099015",
    npwp: "10.221.884.3-012.015",
    ptkp: "TK/0",
    bpjsKes: "0001872211015",
    bpjsTk: "8801122015",
    salary: 18_000_000,
    allowance: 2_000_000,
    skills: ["Brand", "Copywriting", "Campaigns", "Social"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Rudi Melati", relation: "Ayah", phone: "0812-1515-1599" },
    bio: "Menjaga suara Arunika tetap hangat di setiap titik sentuh.",
  }),
  emp({
    id: "gilang",
    nik: "ARK-2024-044",
    name: "Gilang Ramadhan",
    preferredName: "Gilang",
    email: "gilang.ramadhan@arunika.id",
    phone: "0813-1616-1616",
    initials: "GR",
    tone: 3,
    title: "Account Executive",
    department: "sales",
    managerId: "putri",
    location: "Jakarta",
    joinDate: "2024-04-01",
    status: "active",
    contractType: "permanent",
    grade: "IC2",
    gender: "M",
    birthDate: "1996-06-16",
    address: "Jl. Blok M No. 7",
    city: "Jakarta Selatan",
    bankName: "Mandiri",
    bankAccount: "1280099016",
    npwp: "10.221.884.3-012.016",
    ptkp: "TK/0",
    bpjsKes: "0001872211016",
    bpjsTk: "8801122016",
    salary: 12_000_000,
    allowance: 4_000_000,
    skills: ["Sales", "Negotiation", "CRM", "Presentation"],
    certifications: [],
    facilities: ["Laptop", "Transport"],
    emergencyContact: { name: "Dina Ramadhan", relation: "Ibu", phone: "0813-1616-1699" },
    bio: "Memburu pipeline — dan sedang kehilangan ritme kuartal ini.",
  }),
  emp({
    id: "hana",
    nik: "ARK-2024-046",
    name: "Hana Safira",
    preferredName: "Hana",
    email: "hana.safira@arunika.id",
    phone: "0812-1717-1717",
    initials: "HS",
    tone: 4,
    title: "Customer Success",
    department: "sales",
    managerId: "putri",
    location: "Jakarta",
    joinDate: "2024-06-10",
    status: "active",
    contractType: "permanent",
    grade: "IC2",
    gender: "F",
    birthDate: "1997-11-04",
    address: "Jl. Gandaria No. 12",
    city: "Jakarta Selatan",
    bankName: "BCA",
    bankAccount: "1280099017",
    npwp: "10.221.884.3-012.017",
    ptkp: "TK/0",
    bpjsKes: "0001872211017",
    bpjsTk: "8801122017",
    salary: 11_000_000,
    allowance: 1_000_000,
    skills: ["Customer success", "Onboarding", "Writing"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Sari Safira", relation: "Ibu", phone: "0812-1717-1799" },
    bio: "Menjaga klien tetap betah setelah kontrak ditandatangani.",
  }),
  emp({
    id: "iwan",
    nik: "ARK-2023-038",
    name: "Iwan Kurniawan",
    preferredName: "Iwan",
    email: "iwan.kurniawan@arunika.id",
    phone: "0813-1818-1818",
    initials: "IK",
    tone: 5,
    title: "Operations Lead",
    department: "operations",
    managerId: "maya",
    location: "Jakarta",
    joinDate: "2023-07-17",
    status: "active",
    contractType: "permanent",
    grade: "IC3",
    gender: "M",
    birthDate: "1991-09-01",
    address: "Jl. Cilandak No. 16",
    city: "Jakarta Selatan",
    bankName: "BNI",
    bankAccount: "1280099018",
    npwp: "10.221.884.3-012.018",
    ptkp: "K/2",
    bpjsKes: "0001872211018",
    bpjsTk: "8801122018",
    salary: 13_000_000,
    allowance: 1_500_000,
    skills: ["Ops", "Vendor", "Facilities", "Procurement"],
    certifications: [],
    facilities: ["Laptop"],
    emergencyContact: { name: "Tari Kurniawan", relation: "Istri", phone: "0813-1818-1899" },
    bio: "Yang membuat kantor, vendor, dan logistik tidak pernah kelihatan kacau.",
  }),
];

function workingDays(from: string, to: string) {
  const days: string[] = [];
  let cursor = parseISO(from);
  const end = parseISO(to);
  while (cursor <= end) {
    if (!isWeekend(cursor)) days.push(format(cursor, "yyyy-MM-dd"));
    cursor = addDays(cursor, 1);
  }
  return days;
}

function stamp(date: string, hour: number, minute: number) {
  const d = setMinutes(setHours(parseISO(date), hour), minute);
  return d.toISOString();
}

function buildAttendance(): AttendanceRecord[] {
  const days = workingDays("2026-09-01", TODAY);
  const records: AttendanceRecord[] = [];
  for (const employee of EMPLOYEES) {
    for (const date of days) {
      const h = hashString(`${employee.id}-${date}`);
      const id = `att-${employee.id}-${date}`;
      if (employee.id === "kirana" && date === "2026-09-04") {
        records.push({ id, employeeId: employee.id, date, status: "absent", notes: "Tidak ada kabar" });
        continue;
      }
      if (employee.id === "gilang" && date === "2026-09-08") {
        records.push({ id, employeeId: employee.id, date, status: "absent" });
        continue;
      }
      if (employee.id === "farah" && date === "2026-09-03") {
        records.push({
          id,
          employeeId: employee.id,
          date,
          status: "leave",
          notes: "Cuti tahunan",
        });
        continue;
      }
      const late =
        employee.id === "bima"
          ? h % 3 === 0
          : employee.id === "gilang"
            ? h % 4 === 0
            : h % 11 === 0;
      const wfh = employee.id === "maya" ? h % 5 === 0 : employee.id === "nadia" && date === "2026-09-09";
      const inMin = late ? 18 + (h % 25) : 4 + (h % 16);
      const outMin = 20 + (h % 40);
      records.push({
        id,
        employeeId: employee.id,
        date,
        clockIn: stamp(date, late ? 9 : 8, inMin),
        clockOut: date === TODAY ? undefined : stamp(date, 17, outMin),
        clockInLat: COMPANY.officeLat + ((h % 7) - 3) * 0.0004,
        clockInLng: COMPANY.officeLng + ((h % 5) - 2) * 0.0004,
        clockInMethod: wfh ? "gps" : h % 6 === 0 ? "photo" : "office",
        status: wfh ? "wfh" : late ? "late" : "present",
        photoCaptured: h % 6 === 0,
      });
    }
  }
  return records;
}

export const ATTENDANCE = buildAttendance();

export const LEAVE_BALANCES: LeaveBalance[] = EMPLOYEES.map((e) => {
  const used = e.id === "farah" ? 3 : e.id === "bima" ? 8 : e.id === "gilang" ? 6 : e.id === "maya" ? 2 : 1;
  return {
    employeeId: e.id,
    annual: e.contractType === "intern" ? 0 : 12,
    annualUsed: e.contractType === "intern" ? 0 : used,
    sick: 12,
    sickUsed: e.id === "bima" ? 4 : 0,
  };
});

export const LEAVES: LeaveRequest[] = [
  {
    id: "lv-1",
    employeeId: "nadia",
    type: "annual",
    startDate: "2026-09-18",
    endDate: "2026-09-19",
    days: 2,
    reason: "Liburan singkat ke Bandung bersama keluarga.",
    status: "pending",
    approvals: [
      { approverId: "raka", status: "pending" },
      { approverId: "lestari", status: "pending" },
    ],
    createdAt: "2026-09-08T09:12:00.000Z",
  },
  {
    id: "lv-2",
    employeeId: "farah",
    type: "annual",
    startDate: "2026-09-03",
    endDate: "2026-09-03",
    days: 1,
    reason: "Urusan keluarga di Yogyakarta.",
    status: "approved",
    approvals: [
      { approverId: "dimas", status: "approved", at: "2026-09-01T10:00:00.000Z" },
      { approverId: "lestari", status: "approved", at: "2026-09-01T11:20:00.000Z" },
    ],
    createdAt: "2026-08-28T08:00:00.000Z",
  },
  {
    id: "lv-3",
    employeeId: "bima",
    type: "sick",
    startDate: "2026-08-21",
    endDate: "2026-08-22",
    days: 2,
    reason: "Demam dan migrain. Surat dokter terlampir.",
    status: "approved",
    approvals: [{ approverId: "raka", status: "approved", at: "2026-08-21T07:40:00.000Z" }],
    createdAt: "2026-08-21T07:12:00.000Z",
  },
  {
    id: "lv-4",
    employeeId: "gilang",
    type: "permission",
    startDate: "2026-09-15",
    endDate: "2026-09-15",
    days: 1,
    reason: "Mengurus perpanjangan SIM.",
    status: "pending",
    approvals: [{ approverId: "putri", status: "pending" }],
    createdAt: "2026-09-10T14:05:00.000Z",
  },
  {
    id: "lv-5",
    employeeId: "yoga",
    type: "annual",
    startDate: "2026-10-01",
    endDate: "2026-10-03",
    days: 3,
    reason: "Cuti bersama anak masuk sekolah baru.",
    status: "approved",
    approvals: [
      { approverId: "andi", status: "approved", at: "2026-09-06T09:00:00.000Z" },
      { approverId: "lestari", status: "approved", at: "2026-09-06T13:10:00.000Z" },
    ],
    createdAt: "2026-09-05T11:00:00.000Z",
  },
];

function overtimeFor(id: string) {
  if (id === "bima") return 18;
  if (id === "nadia") return 6;
  if (id === "raka") return 4;
  if (id === "gilang") return 2;
  return id === "kirana" ? 0 : 1;
}

function bonusFor(id: string) {
  if (id === "maya") return 5_000_000;
  if (id === "putri") return 1_500_000;
  if (id === "gilang") return 0;
  return 0;
}

export const PAYSLIPS: Payslip[] = EMPLOYEES.flatMap((e) => [
  calcPayslip(e, "2026-08", overtimeFor(e.id), bonusFor(e.id), "published"),
  calcPayslip(e, "2026-09", Math.round(overtimeFor(e.id) * 0.4), 0, "draft"),
]);

export const KPIS: Kpi[] = [
  {
    id: "k1",
    employeeId: "nadia",
    title: "Reliability portal karyawan",
    description: "Error budget layanan ESS di bawah 1%.",
    target: 99.5,
    current: 99.7,
    unit: "%",
    period: "Q3 2026",
    weight: 0.4,
    status: "exceeded",
  },
  {
    id: "k2",
    employeeId: "nadia",
    title: "Delivery fitur payroll",
    description: "Modul PPh 21 & e-slip rilis ke produksi.",
    target: 3,
    current: 3,
    unit: "rilis",
    period: "Q3 2026",
    weight: 0.35,
    status: "on_track",
  },
  {
    id: "k3",
    employeeId: "nadia",
    title: "Mentoring engineer",
    description: "Sesi 1:1 dengan Bima setiap minggu.",
    target: 12,
    current: 9,
    unit: "sesi",
    period: "Q3 2026",
    weight: 0.25,
    status: "on_track",
  },
  {
    id: "k4",
    employeeId: "bima",
    title: "Cycle time pull request",
    description: "Median waktu review sampai merge.",
    target: 24,
    current: 38,
    unit: "jam",
    period: "Q3 2026",
    weight: 0.4,
    status: "behind",
  },
  {
    id: "k5",
    employeeId: "bima",
    title: "Bug produksi",
    description: "Insiden Sev-2 yang disebabkan perubahan sendiri.",
    target: 2,
    current: 4,
    unit: "insiden",
    period: "Q3 2026",
    weight: 0.3,
    status: "behind",
  },
  {
    id: "k6",
    employeeId: "bima",
    title: "Tes otomatis",
    description: "Cakupan tes pada layanan yang dipegang.",
    target: 80,
    current: 61,
    unit: "%",
    period: "Q3 2026",
    weight: 0.3,
    status: "at_risk",
  },
  {
    id: "k7",
    employeeId: "raka",
    title: "Team delivery",
    description: "Sprint goal tercapai tanpa overtime berlebih.",
    target: 90,
    current: 78,
    unit: "%",
    period: "Q3 2026",
    weight: 0.4,
    status: "at_risk",
  },
  {
    id: "k8",
    employeeId: "raka",
    title: "Health check tim",
    description: "Skor pulsa tim (survei 2 mingguan).",
    target: 4,
    current: 3.4,
    unit: "/5",
    period: "Q3 2026",
    weight: 0.3,
    status: "at_risk",
  },
  {
    id: "k9",
    employeeId: "raka",
    title: "Hiring pipeline",
    description: "Kandidat senior backend di tahap onsite.",
    target: 4,
    current: 2,
    unit: "kandidat",
    period: "Q3 2026",
    weight: 0.3,
    status: "behind",
  },
  {
    id: "k10",
    employeeId: "gilang",
    title: "New ARR",
    description: "Kontrak baru tertutup kuartal ini.",
    target: 800,
    current: 240,
    unit: "juta",
    period: "Q3 2026",
    weight: 0.5,
    status: "behind",
  },
  {
    id: "k11",
    employeeId: "gilang",
    title: "Discovery calls",
    description: "Panggilan kualifikasi per bulan.",
    target: 20,
    current: 11,
    unit: "panggilan",
    period: "Q3 2026",
    weight: 0.5,
    status: "behind",
  },
  {
    id: "k12",
    employeeId: "lestari",
    title: "Time to fill",
    description: "Rata-rata hari untuk mengisi posisi kritis.",
    target: 35,
    current: 29,
    unit: "hari",
    period: "Q3 2026",
    weight: 0.4,
    status: "exceeded",
  },
  {
    id: "k13",
    employeeId: "lestari",
    title: "eNPS",
    description: "Employee net promoter score internal.",
    target: 40,
    current: 36,
    unit: "poin",
    period: "Q3 2026",
    weight: 0.35,
    status: "on_track",
  },
  {
    id: "k14",
    employeeId: "lestari",
    title: "Completion review",
    description: "Karyawan dengan paket 360 lengkap.",
    target: 100,
    current: 62,
    unit: "%",
    period: "Q3 2026",
    weight: 0.25,
    status: "at_risk",
  },
  {
    id: "k15",
    employeeId: "farah",
    title: "Design system adoption",
    description: "Komponen baru memakai token Humanis.",
    target: 90,
    current: 84,
    unit: "%",
    period: "Q3 2026",
    weight: 0.5,
    status: "on_track",
  },
  {
    id: "k16",
    employeeId: "hana",
    title: "Retention klien",
    description: "Logo yang diperpanjang kontrak.",
    target: 95,
    current: 100,
    unit: "%",
    period: "Q3 2026",
    weight: 0.6,
    status: "exceeded",
  },
  {
    id: "k17",
    employeeId: "yoga",
    title: "Discovery reviews",
    description: "Masalah tervalidasi sebelum masuk roadmap.",
    target: 8,
    current: 7,
    unit: "brief",
    period: "Q3 2026",
    weight: 0.5,
    status: "on_track",
  },
  {
    id: "k18",
    employeeId: "citra",
    title: "Onboarding 30 hari",
    description: "Karyawan baru menyelesaikan checklist onboarding.",
    target: 100,
    current: 100,
    unit: "%",
    period: "Q3 2026",
    weight: 0.5,
    status: "exceeded",
  },
];

function scores(base: number[]) {
  return COMPETENCIES.map((competency, i) => ({ competency, score: base[i] ?? 3 }));
}

export const REVIEWS: Review[] = [
  {
    id: "rv-1",
    employeeId: "nadia",
    cycle: "Q3 2026",
    type: "self",
    reviewerId: "nadia",
    scores: scores([4, 5, 4, 5, 4]),
    narrative:
      "Saya puas dengan rilis payroll. Yang ingin saya perbaiki: memberi Bima ruang untuk gagal dengan aman, bukan mengambil pekerjaannya.",
    submittedAt: "2026-09-04T10:00:00.000Z",
    status: "submitted",
  },
  {
    id: "rv-2",
    employeeId: "nadia",
    cycle: "Q3 2026",
    type: "manager",
    reviewerId: "raka",
    scores: scores([5, 4, 5, 5, 4]),
    narrative:
      "Nadia adalah tulang punggung tim. Kualitas rilisnya konsisten. Minta ia lebih sering mendelegasikan, bukan menyelesaikan semuanya sendiri.",
    submittedAt: "2026-09-05T08:30:00.000Z",
    status: "submitted",
  },
  {
    id: "rv-3",
    employeeId: "nadia",
    cycle: "Q3 2026",
    type: "peer",
    reviewerId: "farah",
    scores: scores([5, 5, 4, 5, 4]),
    narrative: "Kolaborasi desain–eng paling mulus di studio. Feedbacknya spesifik dan sopan.",
    submittedAt: "2026-09-06T13:00:00.000Z",
    status: "submitted",
  },
  {
    id: "rv-4",
    employeeId: "bima",
    cycle: "Q3 2026",
    type: "self",
    reviewerId: "bima",
    scores: scores([3, 3, 3, 3, 3]),
    narrative: "Saya merasa tertinggal. Banyak kerja malam, hasilnya tidak sebanding.",
    submittedAt: "2026-09-07T21:10:00.000Z",
    status: "submitted",
  },
  {
    id: "rv-5",
    employeeId: "bima",
    cycle: "Q3 2026",
    type: "manager",
    reviewerId: "raka",
    scores: scores([3, 3, 2, 3, 3]),
    narrative: "",
    status: "draft",
  },
  {
    id: "rv-6",
    employeeId: "gilang",
    cycle: "Q3 2026",
    type: "manager",
    reviewerId: "putri",
    scores: scores([2, 3, 2, 3, 2]),
    narrative:
      "Pipeline menipis. Kehadiran tidak stabil. Perlu rencana 30 hari yang sangat konkret, bukan motivasi umum.",
    submittedAt: "2026-09-09T09:00:00.000Z",
    status: "submitted",
  },
];

export const POSITIONS: OpenPosition[] = [
  {
    id: "pos-1",
    title: "Senior Backend Engineer",
    department: "engineering",
    level: "IC3",
    skills: ["Node.js", "PostgreSQL", "System design", "TypeScript", "API design"],
    description:
      "Membangun layanan payroll dan kehadiran yang tahan beban. Lebih suka kandidat internal yang sudah mengenal domain.",
    postedAt: "2026-09-02",
  },
  {
    id: "pos-2",
    title: "People Partner",
    department: "people",
    level: "IC2",
    skills: ["Employee relations", "Coaching", "Onboarding", "People ops"],
    description: "Dampingi manajer di squad produk. Cocok untuk HRBP yang sudah mengenal kultur Arunika.",
    postedAt: "2026-09-07",
  },
];

export const CLAIMS: Claim[] = [
  {
    id: "cl-1",
    employeeId: "nadia",
    type: "medical",
    amount: 450_000,
    date: "2026-09-02",
    description: "Pemeriksaan dokter umum dan obat demam.",
    status: "paid",
    receiptName: "kwitansi-rs-pondok-indah.pdf",
  },
  {
    id: "cl-2",
    employeeId: "bima",
    type: "transport",
    amount: 180_000,
    date: "2026-09-09",
    description: "Taksi malam setelah rilis hotfix.",
    status: "pending",
    receiptName: "grab-0909.jpg",
  },
  {
    id: "cl-3",
    employeeId: "farah",
    type: "wellness",
    amount: 350_000,
    date: "2026-08-28",
    description: "Sesi fisioterapi bahu.",
    status: "approved",
    receiptName: "fisio-agustus.pdf",
  },
];

export const DOCS: CompanyDoc[] = [
  {
    id: "doc-pp",
    title: "Peraturan Perusahaan 2026",
    category: "handbook",
    updatedAt: "2026-01-15",
    summary: "Hak, kewajiban, jam kerja, dan sanksi di PT Arunika Digital.",
    content:
      "Jam kerja reguler 09.00–18.00 WIB, Senin–Jumat, dengan fleksibilitas 08.30–09.30 untuk clock-in. Hybrid maksimal 2 hari per minggu dengan persetujuan atasan. Cuti tahunan 12 hari kerja setelah 12 bulan masa kerja. Karyawan magang tidak mendapatkan cuti tahunan, hanya izin sakit dengan surat dokter.",
  },
  {
    id: "doc-cuti",
    title: "SOP Cuti & Izin",
    category: "sop",
    updatedAt: "2026-03-02",
    summary: "Alur pengajuan, persetujuan berjenjang, dan dokumentasi.",
    content:
      "Cuti tahunan diajukan minimal 7 hari sebelumnya melalui portal. Izin 1 hari cukup disetujui atasan langsung. Cuti lebih dari 1 hari membutuhkan persetujuan atasan lalu People. Cuti sakit 2 hari atau lebih wajib menyertakan surat dokter. Sisa cuti tidak boleh negatif. Carry-over maksimal 6 hari ke tahun berikutnya, hangus pada 31 Maret.",
  },
  {
    id: "doc-klaim",
    title: "Kebijakan Klaim Kesehatan",
    category: "policy",
    updatedAt: "2026-02-20",
    summary: "Plafon rawat jalan, kuitansi, dan waktu penggantian.",
    content:
      "Plafon rawat jalan karyawan: Rp 3.000.000 / tahun. Tanggungan inti (suami/istri/anak) mengikuti asuransi. Klaim diajukan maksimal 14 hari setelah transaksi dengan kuitansi bermaterai jika di atas Rp 5.000.000. Penggantian diproses setiap Jumat bersama payroll jika disetujui sebelum Rabu 12.00.",
  },
  {
    id: "doc-lembur",
    title: "SOP Lembur",
    category: "sop",
    updatedAt: "2026-04-11",
    summary: "Syarat, persetujuan, dan perhitungan upah lembur.",
    content:
      "Lembur hanya sah jika disetujui atasan sebelum dikerjakan, kecuali insiden produksi. Jam pertama 1,5× upah sejam, jam berikutnya 2×. Upah sejam = gaji pokok / 173. Lembur tidak menggantikan kekurangan perencanaan sprint. People akan menandai pola lembur berlebih sebagai sinyal kesejahteraan.",
  },
  {
    id: "doc-hybrid",
    title: "Kebijakan Hybrid & Presensi",
    category: "policy",
    updatedAt: "2026-05-08",
    summary: "GPS, foto, dan radius kantor.",
    content:
      "Clock-in dapat dilakukan via GPS (radius 250 m dari kantor) atau foto seluler. Kerja jarak jauh dicatat sebagai WFH dan tidak membutuhkan foto. Keterlambatan dihitung setelah 09:15. Empat kali terlambat dalam sebulan memicu percakapan dengan atasan, bukan sanksi otomatis.",
  },
  {
    id: "doc-payroll-int",
    title: "SOP Integrasi Payroll",
    category: "sop",
    updatedAt: "2026-09-04",
    summary: "Alur kirim master ke Accurate, tarik hitungan, unggah file bank dan e-Bupot.",
    content:
      "Humanis adalah sumber data orang. Perhitungan gaji resmi tetap di Accurate Online milik Finance. Setiap tanggal 22, People mengirim master karyawan, rekap kehadiran, jam lembur, dan klaim yang sudah disetujui. Finance menutup hitungan di Accurate paling lambat tanggal 24. Tanggal 25 People menarik hasil (PPh 21, BPJS, take-home), menerbitkan e-slip, lalu mengunduh file BCA Multi Credit dan CSV e-Bupot Unifikasi. Magang tanpa NPWP dilewati di e-Bupot. Jangan kirim file bank sebelum slip berstatus terbit. Kode objek pajak pegawai tetap: 21-100-01.",
  },
];

export const RETENTION: RetentionSignal[] = [
  {
    employeeId: "bima",
    risk: "high",
    score: 78,
    factors: ["Keterlambatan berulang", "Lembur 18 jam di Agustus", "KPI tertinggal", "Nada review diri rendah"],
    sentiment: -0.42,
  },
  {
    employeeId: "gilang",
    risk: "high",
    score: 71,
    factors: ["Pipeline jauh di bawah target", "Absen tanpa kabar 8 Sep", "Skor atasan rendah"],
    sentiment: -0.35,
  },
  {
    employeeId: "kirana",
    risk: "medium",
    score: 54,
    factors: ["Magang baru 2 bulan", "Satu hari absen", "Belum punya mentor formal"],
    sentiment: 0.1,
  },
  {
    employeeId: "raka",
    risk: "medium",
    score: 48,
    factors: ["Beban manajerial + hiring", "Pulsa tim menurun"],
    sentiment: 0.05,
  },
  {
    employeeId: "nadia",
    risk: "low",
    score: 18,
    factors: ["Kinerja tinggi", "Kehadiran stabil"],
    sentiment: 0.62,
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: "msg-0",
    role: "assistant",
    content:
      "Saya asisten People Arunika. Tanya saja sisa cuti, cara klaim medis, syarat lembur, atau kebijakan hybrid — saya jawab dari peraturan perusahaan yang berlaku.",
    at: "2026-09-11T08:00:00.000Z",
  },
];

export const CONNECTORS: PayrollConnector[] = [
  {
    id: "accurate",
    status: "connected",
    environment: "production",
    companyCode: "ARK-ACC-8821",
    connectedAt: "2026-03-12T09:00:00.000Z",
    lastSyncAt: "2026-09-10T16:42:00.000Z",
  },
  {
    id: "talenta",
    status: "disconnected",
    environment: "sandbox",
  },
  {
    id: "jurnal",
    status: "disconnected",
    environment: "production",
  },
  {
    id: "sap",
    status: "disconnected",
    environment: "production",
  },
  {
    id: "excel",
    status: "connected",
    environment: "production",
    connectedAt: "2026-01-08T08:00:00.000Z",
    lastSyncAt: "2026-09-10T16:42:00.000Z",
  },
  {
    id: "bca",
    status: "connected",
    environment: "production",
    companyCode: "BCA-MC-7781",
    connectedAt: "2026-04-02T10:00:00.000Z",
    lastSyncAt: "2026-08-25T11:05:00.000Z",
  },
  {
    id: "ebupot",
    status: "connected",
    environment: "production",
    companyCode: "10.221.884.3-012.000",
    connectedAt: "2026-04-02T10:10:00.000Z",
    lastSyncAt: "2026-09-05T09:18:00.000Z",
  },
];

export const SYNC_JOBS: SyncJob[] = [
  {
    id: "sync-seed-1",
    providerId: "accurate",
    kind: "full",
    status: "partial",
    startedAt: "2026-09-10T16:40:12.000Z",
    finishedAt: "2026-09-10T16:42:01.000Z",
    pushed: 18,
    pulled: 17,
    skipped: 1,
    message: "Sinkron penuh: 18 kirim, 17 tarik. 1 baris dilewati.",
  },
  {
    id: "sync-seed-2",
    providerId: "accurate",
    kind: "master",
    status: "success",
    startedAt: "2026-09-08T09:02:00.000Z",
    finishedAt: "2026-09-08T09:02:41.000Z",
    pushed: 18,
    pulled: 0,
    skipped: 0,
    message: "Mengirim 18 master karyawan ke payroll lokal.",
  },
  {
    id: "sync-seed-3",
    providerId: "bca",
    kind: "bank_file",
    status: "success",
    startedAt: "2026-08-25T11:04:12.000Z",
    finishedAt: "2026-08-25T11:05:02.000Z",
    pushed: 18,
    pulled: 0,
    skipped: 0,
    message: "Berkas transfer 18 rekening siap diunggah.",
  },
  {
    id: "sync-seed-4",
    providerId: "ebupot",
    kind: "tax_file",
    status: "partial",
    startedAt: "2026-09-05T09:17:20.000Z",
    finishedAt: "2026-09-05T09:18:04.000Z",
    pushed: 17,
    pulled: 0,
    skipped: 1,
    message: "Berkas e-Bupot 17 WP. 1 baris dilewati.",
  },
];

export const TODAY_ISO = TODAY;
