/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppAttendanceRouteImport } from './routes/app/attendance'
import { Route as AppClaimsRouteImport } from './routes/app/claims'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppEmployeesRouteImport } from './routes/app/employees'
import { Route as AppIntegrationsRouteImport } from './routes/app/integrations'
import { Route as AppKpiRouteImport } from './routes/app/kpi'
import { Route as AppLeaveRouteImport } from './routes/app/leave'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppMobilityRouteImport } from './routes/app/mobility'
import { Route as AppOrgRouteImport } from './routes/app/org'
import { Route as AppPayrollRouteImport } from './routes/app/payroll'
import { Route as AppPerformanceRouteImport } from './routes/app/performance'
import { Route as AppRetentionRouteImport } from './routes/app/retention'
import { Route as AppEmployeesIdRouteImport } from './routes/app/employees.$id'
import { Route as AppPayrollIdRouteImport } from './routes/app/payroll.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppClaimsRoute = AppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMobilityRoute = AppMobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppRetentionRoute = AppRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppPayrollIdRoute = AppPayrollIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPayrollRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/masuk': typeof MasukRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/claims': typeof AppClaimsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/org': typeof AppOrgRoute
  '/app/payroll': typeof AppPayrollRouteWithChildren
  '/app/performance': typeof AppPerformanceRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$id': typeof AppPayrollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/claims': typeof AppClaimsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/org': typeof AppOrgRoute
  '/app/payroll': typeof AppPayrollRouteWithChildren
  '/app/performance': typeof AppPerformanceRoute
  '/app/retention': typeof AppRetentionRoute
  '/app': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$id': typeof AppPayrollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/masuk': typeof MasukRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/claims': typeof AppClaimsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/org': typeof AppOrgRoute
  '/app/payroll': typeof AppPayrollRouteWithChildren
  '/app/performance': typeof AppPerformanceRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$id': typeof AppPayrollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/masuk'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/claims'
    | '/app/docs'
    | '/app/employees'
    | '/app/integrations'
    | '/app/kpi'
    | '/app/leave'
    | '/app/me'
    | '/app/mobility'
    | '/app/org'
    | '/app/payroll'
    | '/app/performance'
    | '/app/retention'
    | '/app/'
    | '/app/employees/$id'
    | '/app/payroll/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/masuk'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/claims'
    | '/app/docs'
    | '/app/employees'
    | '/app/integrations'
    | '/app/kpi'
    | '/app/leave'
    | '/app/me'
    | '/app/mobility'
    | '/app/org'
    | '/app/payroll'
    | '/app/performance'
    | '/app/retention'
    | '/app'
    | '/app/employees/$id'
    | '/app/payroll/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/masuk'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/claims'
    | '/app/docs'
    | '/app/employees'
    | '/app/integrations'
    | '/app/kpi'
    | '/app/leave'
    | '/app/me'
    | '/app/mobility'
    | '/app/org'
    | '/app/payroll'
    | '/app/performance'
    | '/app/retention'
    | '/app/'
    | '/app/employees/$id'
    | '/app/payroll/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MasukRoute: typeof MasukRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/claims': {
      id: '/app/claims'
      path: '/claims'
      fullPath: '/app/claims'
      preLoaderRoute: typeof AppClaimsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpi': {
      id: '/app/kpi'
      path: '/kpi'
      fullPath: '/app/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mobility': {
      id: '/app/mobility'
      path: '/mobility'
      fullPath: '/app/mobility'
      preLoaderRoute: typeof AppMobilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retention': {
      id: '/app/retention'
      path: '/retention'
      fullPath: '/app/retention'
      preLoaderRoute: typeof AppRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/app/payroll/$id': {
      id: '/app/payroll/$id'
      path: '/$id'
      fullPath: '/app/payroll/$id'
      preLoaderRoute: typeof AppPayrollIdRouteImport
      parentRoute: typeof AppPayrollRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppPayrollRouteChildren {
  AppPayrollIdRoute: typeof AppPayrollIdRoute
}

const AppPayrollRouteChildren: AppPayrollRouteChildren = {
  AppPayrollIdRoute: AppPayrollIdRoute,
}

const AppPayrollRouteWithChildren = AppPayrollRoute._addFileChildren(
  AppPayrollRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClaimsRoute: typeof AppClaimsRoute
  AppDocsRoute: typeof AppDocsRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKpiRoute: typeof AppKpiRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMeRoute: typeof AppMeRoute
  AppMobilityRoute: typeof AppMobilityRoute
  AppOrgRoute: typeof AppOrgRoute
  AppPayrollRoute: typeof AppPayrollRouteWithChildren
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppRetentionRoute: typeof AppRetentionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppClaimsRoute: AppClaimsRoute,
  AppDocsRoute: AppDocsRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKpiRoute: AppKpiRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMeRoute: AppMeRoute,
  AppMobilityRoute: AppMobilityRoute,
  AppOrgRoute: AppOrgRoute,
  AppPayrollRoute: AppPayrollRouteWithChildren,
  AppPerformanceRoute: AppPerformanceRoute,
  AppRetentionRoute: AppRetentionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MasukRoute: MasukRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
